### PR TITLE
Added Files and updated configs that will fix java policy issues

### PR DESCRIPTION
**Pull request by mark-monserrat**
1. Added java.policy
2. Fix issues on java policy i.e. permission issue in `javax.management.MBeanTrustPermission "register"`

### CODE REVIEW

**Comment by pgbezerra** [comment]
Hi @mark-monserrat, where you get this policy file?  
Is it provided by ElasticSearch team, or something like that?

**Comment by mark-monserrat** [comment]
@paulobezerr , I curated it my self based on the errors that I have encountered everytime I run the docker. The error message displays the required permission which is not available on the default java policy. So I edited the default java.policy file and added the policies that are reqired during runtime.

**Comment by khezen** [comment]
@paulobezerr 
Are you able to reproduce the issue as well?

**Comment by mark-monserrat** [comment]
@khezen @paulobezerr I'm sorry to report an issue without any complete details. I will document the steps on how to reproduce the errors. But maybe later this weekend, I'm just too busy right now at work.

**Comment by pgbezerra** [comment]
I can't, @khezen.
I asked because I worried about security, some params open java to write in some contexts.

**Comment by rajendramarati** [comment]
Hi Mark-monserrat,

I am still facing this issue after adding the permission in the java.policy file.
This is happening with Jboss 7.0.0 EAP and JDK 1.8.0_141 versions.
Also, the issue is not occurring every time of restart of app services but only sometimes.
Can you please share the steps to reproduce and how to fix this permanently?

**Comment by rajendramarati** [comment]
Hi Mark-monserrat,

I am still facing this issue after adding the permission in the java.policy file.
This is happening with Jboss 7.0.0 EAP and JDK 1.8.0_141 versions.
Also, the issue is not occurring every time of restart of app services but only sometimes.
Can you please share the steps to reproduce and how to fix this permanently?

**Comment by khezen** [comment]
inactive for more than one year.

**Pull request closed without merging**
